export const QueryKeys = {
  USER_INFO: "USER_INFO",
  SOCIAL_LOGIN: "SOCIAL_LOGIN",

  MOVIES: "MOVIES",
  ACTORS: "ACTORS",
  GENRES: "GENRES",
  KEYWORDS: "KEYWORDS",
  COUNTRIES: "COUNTRIES",
  SERIES: "SERIES",
  REPORTS: "REPORTS",

  EPISODES: "EPISODES",
  NOTIFICATIONS: "NOTIFICATIONS",

  // Follow & Review
  FOLLOW_STATUS: "FOLLOW_STATUS",
  USER_REVIEW: "USER_REVIEW",
};
